service: environmentally-challenged-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment: 
    DB_HOST: ${file(./config.${self:provider.stage}.json):DB_HOST}
    DB_USER: ${file(./config.${self:provider.stage}.json):DB_USER}
    DB_PASSWORD: ${file(./config.${self:provider.stage}.json):DB_PASSWORD}
    DB_SCHEMA: ${file(./config.${self:provider.stage}.json):DB_SCHEMA}

functions:
  challenge:
    handler: handler.challenge
    events: 
      - http:
          path: challenge
          method: get
          cors: true
      - http:
          path: challenge/{challengeId}
          method: put
          cors: true
      - http:
          path: challenge
          method: post
          cors: true
      - http:
          path: challenge/{challengeId}
          method: delete
          cors: true
